name: Merge main branch to cf
on:
  push:
    branches:
      - 'main'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> main-cf
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: main-cf
          github_token: ${{ secrets.GITHUB_TOKEN }}